version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ":seedling:"
    assignees:
      - "jquagga"
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ":seedling:"
    assignees:
      - "jquagga"
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ":seedling:"
    assignees:
      - "jquagga"
